### ISSUE TITLE
Continuous lag spikes due to GUILD_ROSTER_UPDATE

### ISSUE THREAD

**Issue by Bonkeybee** [fjaros/cleangroupassigns#2]
I'm in a guild with 1000 members and the FillPlayerBank() that is called on every "GUILD_ROSTER_UPDATE" is inefficient and causes massive lag spikes.

Either find a way to preserve the scrollframe and playerlabels so they are not reconstructed every call or add a manual refresh button. Unless you can think of a better way.

For now I've edited the addon myself and it only will call FillPlayerBank() once per /reload

**Comment by fjaros** [comment]
Good call-out. I'm not in a big guild so I don't experience this issue. I'll find a way to better hold the state to prevent full redraw each update.

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/cleangroupassigns/commit/69aefdfc583f1d3150c430055cfa326d0422d154 -> v1.1 on curseforge.
