### ISSUE TITLE
Cannot rearrange in combat

### ISSUE THREAD

**Issue by antoine-delh** [fjaros/cleangroupassigns#4]
Works perfectly out of combat, but not while in combat. It prompts that it is rearranging, but never complete anything. If started on another preset, says to wait for current rearrangement to finish. Manually moving one player from one group to another unblocks the situation and the rearrangement completes.

**Comment by fjaros** [comment]
The addon should not allow arranging in combat as that is impossible to do. Blizzard does not allow addons to rearrange group members in combat. The only way to do it is manually via the regular blizzard raid group window. I'll make that be a clear message in the next version.
